### ISSUE TITLE
Implement new song import script

### ISSUE THREAD

**Issue by abigaelkimani** [briankiragu/projectr#13]
1. adding a new song

**Comment by briankiragu** [comment]
In the interest of progress, this feature will be converted to "Implement new song import script"

**Comment by abigaelkimani** [comment]
> 1. adding a new song

**Comment by abigaelkimani** [comment]
Dear Kariuki,

Sorry, you lost me here! what's implementing new song import script?

Regards,

**Comment by abigaelkimani** [comment]
Hello Kariuki,

Kindly let's catch up on Sunday Morning on all these updates.

Regards,

Ngari
